
CREATE TABLE Users(id INT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(100));
CREATE TABLE Bookings(id INT PRIMARY KEY AUTO_INCREMENT,user_id INT);
CREATE TABLE Payments(id INT PRIMARY KEY AUTO_INCREMENT);
